apiVersion: batch/v1
kind: Job
metadata:
  name: lcs-5-job
spec:
  template:
    spec:
      containers:
      - name: create-html
        image: alpine:latest
        command: ["sh", "-c", "echo '<html><body><h1>JOB DEPLOYED SUCCESSFULLY</h1></body></html>' > /usr/share/nginx/html/index.html"]
        volumeMounts:
        - name: lcs-5-nfs-storage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: lcs-5-nfs-storage
        persistentVolumeClaim:
          claimName: test-dynamic-volume-claim
      restartPolicy: Never

